name: compspace
channels:
  - conda-forge
dependencies:
  - numpy
  - matplotlib
  - pytest
  - pandas
  - numba
  - h5py
  - scikit-learn
  - tqdm
  - pyevtk
  - ipywidgets
  - pyyaml
  - ipyvtklink
  - pyvista
  - ipywidgets
  - panel
